<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sVisearch %s'), '<span class="zf-green">', '</span>') ?></h1>
    
    <p>
    System rankingu obrazów stworzony w Katedrze Metod Matematycznych Informatyki wydział Matematyki i Informatyki UWM. 
    
    <?php /* echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. 
    		You are currently running Zend Framework version %s. This skeleton can serve as a simple 
    		starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) 
    		
    		*/
    		?>
    </p>
    
    <p><a class="btn btn-success btn-lg" href="https://wmii.uwm.edu.pl" target="_blank">Wydział Matematyki i Informatyki &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Metody</h3>
            </div>
            <div class="panel-body">
                <p>System stworzony w oparciu o metody Bags of Words</p>
            
                <p>
                <a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a>
                
                </p>
            
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Osoby zaangażowane</h3>
            </div>
            <div class="panel-body">
                <ul>
                <li> </li>
                <li> </li>
                <li> </li>
                <li> </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Publikacje </h3>
                
            </div>
            <div class="panel-body">
                
            </div>
        </div>
    </div>
</div>
