<?php


 $title = 'Images';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <table class="table">
 <tr>
     <th>Id</th>
     <th>FileName</th>
     <th>FileDirectory</th>
     <th>Url</th>
     <th>Created</th>
     <th>ImPath</th>
      <th>&nbsp;</th>
 </tr>
 <?php foreach ($images as $im) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($im->imageId);?></td>
     <td><?php echo $this->escapeHtml($im->fileName);?></td>
     <td><?php echo $this->escapeHtml($im->fileDirectory);?></td>
     <td><?php echo $this->escapeHtml($im->url);?></td>
     <td><?php echo $this->escapeHtml($im->created);?></td>
     <td><img src="<?php echo $this->escapeHtml($im->imagePath);?>" alt="<?php echo $this->escapeHtml($im->imageId);?>" /></td>
     <td>
         <a href="#">Edit</a>
         <a href="#">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>