<?php


 $title = 'Search Image Ranking';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <div>
 <p>
 Image id comes from query string, default images 1 eg. http://visearch.uwm.eudu.pl/search/searchranking/4 
 </p>
 
 
 <div id="imageInfo">
 
 <div id="imageBlock">
 <img src="<?php echo $image->imagePath ?>" alt="<?php echo $image->imageId?>" />
 <p>
 Image ID= <?php echo $imgRep['ImageId']; ?> <br/>
 Scoring: <strong>Euclidean</strong> <br/>
 </p>
 </div>
 
 <div id="imageRepresentation">
 <strong>Image Representation:</strong> 
 <pre>
<?php echo $imgRep['Representation']; ?>
 </pre>
 </div>
 
 
 </div>
 
 </div>
 
 
 <h2>Search results</h2>
  
 <?php if(empty($images)) echo "Empty search resultss!" ?>
 <?php if( isset($msg)) echo $msg ?> 
  
  
 <ol>
 <?php foreach ($images as $im) : ?>
 <li>
 <a href="<?php echo $this->url('search',array('action'=>'searchranking', 'id'=>$im->imageId))?>">
 	<img src="<?php echo $this->escapeHtml($im->path);?>" alt="<?php echo $this->escapeHtml($im->imageId);?>" />
    
 	</a>
    
     
     <strong> Id: <?php echo $this->escapeHtml($im->imageId);?></strong>
     <strong> Score: <?php echo $this->escapeHtml($im->score);?></strong>
</li>     
 <?php endforeach; ?>
 </ol>
 
 
 
 
 
 
 
 
 
 
 
 