<?php


 $title = 'Search Image Ranking';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <div>
 <h2>Query Image from Database</h2>
 <p>
 Image id comes from url, default 1 eg. http://visearch/search/searchranking/4 
 </p>
 <img src="<?php echo $image->imagePath ?>" alt="<?php echo $imge->imageId?>" />
 
 
 <p>
 Image ID= <?php echo $imgRep['ImageId']; ?> <br/>
 Scoring: <strong>Euclidean</strong> <br/>
 
 <strong>Image Representation:</strong> 
 <pre>
<?php echo $imgRep['Representation']; ?>
 </pre>
 
 </p>
 
 </div>
 
 
 <h2>Image results</h2>
  
 <ol>

 <?php foreach ($images as $im) : ?>
 
 <li>
 <a href="<?php echo $this->url('search',array('action'=>'searchranking', 'id'=>$im->imageId))?>">
 	<img src="<?php echo $this->escapeHtml($im->path);?>" alt="<?php echo $this->escapeHtml($im->imageId);?>" />
    
 	</a>
    
     
     <strong> Id: <?php echo $this->escapeHtml($im->imageId);?></strong>
     <strong> Score: <?php echo $this->escapeHtml($im->score);?></strong>
</li>     
 <?php endforeach; ?>
 </ol>
 
 
 
 
 
 
 
 
 
 
 
 